### PR TITLE
0.4 Release

### PR DESCRIPTION
**Pull request by SenorPez**
Release of 0.4.

### CODE REVIEW

**Comment by SenorPez** [comment]
If I had to make a decision right now, I would say that this pull request is never going to get accepted. There are far too many small issues that are being found, and combined with the relative lack of interest, it's better for my sanity to continue on with the 0.4-rewrite branch (to be renamed 0.5 or maybe just merged into and replace 0.4-devel).

If you are interested in a slightly unstable release, please let me know in the comments so that I know there's interest out there. Otherwise, I'm going to let this continue gathering dust and focus on creating a more stable, tested, and robust product for the next release.

**Comment by Michel-NL** [comment]
Hi SenorPez,

Still following this project, but don't have the time to test it. Also I read your post on the forums that this build will not be the best for multiplayer.
Next month our Project Cars competition will begin and then I will be starting to active test ReplayEnhancer again.

Maybe this weekend I will join some online (quick) races and could test this branch. Or should i skip this branch and wait for a more stable version?

**Comment by SenorPez** [comment]
@Michel-NL 
At this point, the 0.4-devel branch should work okay for the majority of multiplayer races, so if you'd like to use the new graphics, it should work. I'm just not sure it's complete enough to warrant a release!

**Comment by SenorPez** [comment]
Never :shipit:

**Pull request closed without merging**
